<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyobjet($obj){
    $querry = $this->getEntityManager()->createQuery("select r from ReclamationBundle:Reclamation r where r.objet=$obj; ");
    return $querry->getResult();
}
}
