annonce_homepage:
    path:     /
    defaults: { _controller: AnnonceBundle:Default:index }

ajouter_annonce:
    path:     /AjouterAnnonce
    defaults: { _controller: AnnonceBundle:Annonce:AjouterAnnonce }

afficher_annonce:
    path:     /AfficherAnnonce
    defaults: { _controller: AnnonceBundle:Annonce:AfficherAnnonce }

supprimer:
    path:     /SupprimerAnnonce/{id}
    defaults: { _controller: AnnonceBundle:Annonce:SupprimerAnnonce }

modifier_annonce:
    path:     /ModifierAnnonce/{id}
    defaults: { _controller: AnnonceBundle:Annonce:ModifierAnnonce }

ajouter_candidature:
    path:     /AjouterCandidature/{id}
    defaults: { _controller: AnnonceBundle:Candidature:AjouterCandidature }

accepter_candidature:
    path:     /AccepterCandidature/{id}
    defaults: { _controller: AnnonceBundle:Candidature:AccepterCandidature }

refuser_candidature:
    path:     /DeclinerCandidature/{id}
    defaults: { _controller: AnnonceBundle:Candidature:DeclinerCandidature }

afficher_candidature_utilisateur:
    path:     /AfficherCandidatureParUtilisateur
    defaults: { _controller: AnnonceBundle:Candidature:AfficherCandidatureParUtilisateur }

afficher_candidature:
    path:     /AfficherCandidatures
    defaults: { _controller: AnnonceBundle:Candidature:AfficherCandidatures }

recherche:
    path:     /rechercher
    defaults: { _controller: AnnonceBundle:Annonce:chercher }

rechercherAnnonce:
    path:     /RechercherParDomaine
    defaults: { _controller: AnnonceBundle:Annonce:RechercheDomaineDQL }

afficher_annonce_part:
    path:     /AfficherAnnonceParPartenaire
    defaults: { _controller: AnnonceBundle:Annonce:AfficherAnnonces }
show_detail_candidature:
    path:     /show/{id}
    defaults: { _controller: AnnonceBundle:Candidature:showCandidature }

AfficherAnnonceParPartenairee:
    path:     /AfficherAnnonceParPartenairee
    defaults: { _controller: AnnonceBundle:Annonce:AfficherAnnonces }



