annonce_homepage:
    path:     /
    defaults: { _controller: AnnonceBundle:Default:index }

ajouter:
    path:     /AjouterAnnonce
    defaults: { _controller: AnnonceBundle:Annonce:AjouterAnnonce }

afficher:
    path:     /AfficherAnnonce
    defaults: { _controller: AnnonceBundle:Annonce:AfficherAnnonce }

supprimer:
    path:     /SupprimerAnnonce/{id}
    defaults: { _controller: AnnonceBundle:Annonce:SupprimerAnnonce }

modifier:
    path:     /ModifierAnnonce/{id}
    defaults: { _controller: AnnonceBundle:Annonce:ModifierAnnonce }

ajouter_candidature:
    path:     /AjouterCandidature
    defaults: { _controller: AnnonceBundle:Candidature:AjouterCandidature }

recherche:
    path:     /rechercher
    defaults: { _controller: AnnonceBundle:Annonce:chercher }