pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
<<<<<<< HEAD
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /
demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /Demande
=======
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /Demande

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

product:
    resource: "@ProductBundle/Resources/config/routing.yml"

>>>>>>> 9f77a506f8f8fc2ae5306b215fb892a091701742
product_services:
    resource: "@ProductBundle/Resources/config/routing/services.yml"
    prefix:   /services
Commande:
    resource: "@ProductBundle/Resources/config/routing/Commande.yml"
<<<<<<< HEAD
    prefix:   /C
product:
    resource: "@ProductBundle/Resources/config/routing/produits.yml"
    prefix:   /produits
=======
    prefix:   /

>>>>>>> 9f77a506f8f8fc2ae5306b215fb892a091701742
product_produitherbo:
    resource: "@ProductBundle/Resources/config/routing/produitherbo.yml"
    prefix:   /pherbo
product_produitpharmaceutique:
    resource: "@ProductBundle/Resources/config/routing/produitpharmaceutique.yml"
    prefix:   /ppharma
product_produitparapharmacie:
    resource: "@ProductBundle/Resources/config/routing/produitparapharmacie.yml"
    prefix:   /ppara
product_produitsalledesport:
    resource: "@ProductBundle/Resources/config/routing/produitsalledesport.yml"
    prefix:   /produitsalledesport
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
<<<<<<< HEAD
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
=======

    prefix:   /psalledesport

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv

actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
>>>>>>> 9f77a506f8f8fc2ae5306b215fb892a091701742
fiche:
    resource: "@FicheBundle/Resources/config/routing.yml"
    prefix:   /fiche
etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
<<<<<<< HEAD
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications
=======
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications

>>>>>>> 9f77a506f8f8fc2ae5306b215fb892a091701742

