<<<<<<< HEAD
=======
<<<<<<< HEAD
pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product
=======
<<<<<<< HEAD
>>>>>>> f139aee60e6c58f2b36220c9e67bca0120e5914f
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /Demande

product_services:
    resource: "@ProductBundle/Resources/config/routing/services.yml"
    prefix:   /services
Commande:
    resource: "@ProductBundle/Resources/config/routing/Commande.yml"
    prefix:   /
product:
    resource: "@ProductBundle/Resources/config/routing/produits.yml"
    prefix:   /produits
product_produitherbo:
    resource: "@ProductBundle/Resources/config/routing/produitherbo.yml"
    prefix:   /pherbo
product_produitpharmaceutique:
    resource: "@ProductBundle/Resources/config/routing/produitpharmaceutique.yml"
    prefix:   /ppharma
product_produitparapharmacie:
    resource: "@ProductBundle/Resources/config/routing/produitparapharmacie.yml"
    prefix:   /ppara
>>>>>>> bdc2440475f198a081bbf4b7e976fa57d78aa023
product_produitsalledesport:
    resource: "@ProductBundle/Resources/config/routing/produitsalledesport.yml"
<<<<<<< HEAD
=======
<<<<<<< 29a155a2e7356d115a3b73e42bd0caf06b34e55a
    prefix:   /produitsalledesport
<<<<<<< HEAD
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
=======


=======
>>>>>>> f139aee60e6c58f2b36220c9e67bca0120e5914f
    prefix:   /psalledesport
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
>>>>>>> bdc2440475f198a081bbf4b7e976fa57d78aa023
fiche:
    resource: "@FicheBundle/Resources/config/routing.yml"
    prefix:   /fiche
etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
<<<<<<< HEAD
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications
=======
>>>>>>> bdc2440475f198a081bbf4b7e976fa57d78aa023

