pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
<<<<<<< HEAD
=======
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /
demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /Demande

>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product

<<<<<<< HEAD
=======

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"


ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

<<<<<<< HEAD

=======
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /Demande

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

product:
    resource: "@ProductBundle/Resources/config/routing.yml"

<<<<<<< HEAD
=======

>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
product_services:
    resource: "@ProductBundle/Resources/config/routing/services.yml"
    prefix:   /services
Commande:
    resource: "@ProductBundle/Resources/config/routing/Commande.yml"
<<<<<<< HEAD
    prefix:   /
=======

    prefix:   /C
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
product:
    resource: "@ProductBundle/Resources/config/routing/produits.yml"
    prefix:   /produits

    prefix:   /


product_produitherbo:
    resource: "@ProductBundle/Resources/config/routing/produitherbo.yml"
    prefix:   /pherbo
product_produitpharmaceutique:
    resource: "@ProductBundle/Resources/config/routing/produitpharmaceutique.yml"
    prefix:   /ppharma
product_produitparapharmacie:
    resource: "@ProductBundle/Resources/config/routing/produitparapharmacie.yml"
    prefix:   /ppara
product_produitsalledesport:
    resource: "@ProductBundle/Resources/config/routing/produitsalledesport.yml"
<<<<<<< HEAD
    prefix:   /produitsalledesport
=======

>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
<<<<<<< HEAD
=======

rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141


    prefix:   /psalledesport

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
<<<<<<< HEAD

=======
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141

actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites

pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
<<<<<<< HEAD

=======
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
fiche:
    resource: "@FicheBundle/Resources/config/routing.yml"
    prefix:   /fiche
etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
<<<<<<< HEAD
=======
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications
>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications
<<<<<<< HEAD
=======

>>>>>>> d641a5c9c4b1638dce2bc50436cf22e17e6ba141

