<<<<<<< HEAD
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

=======
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

product_produitsalledesport:
    resource: "@ProductBundle/Resources/config/routing/produitsalledesport.yml"
    prefix:   /produitsalledesport


annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
>>>>>>> 081fd7b3694505db4b88ebb4d58c06268a300364
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
<<<<<<< HEAD
=======
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
<<<<<<< HEAD

=======
>>>>>>> 081fd7b3694505db4b88ebb4d58c06268a300364

>>>>>>> fbaf7f05c916b30d5472dc006eb72d9ff341622f
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites


pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /

fiche:
    resource: "@FicheBundle/Resources/config/routing.yml"
    prefix:   /fiche

etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
