pidev_esbe:
    resource: "@PidevEsbeBundle/Resources/config/routing.yml"
    prefix:   /
annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce
product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product
product_produitsalledesport:
    resource: "@ProductBundle/Resources/config/routing/produitsalledesport.yml"
    prefix:   /produitsalledesport
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
actualites:
    resource: "@ActualitesBundle/Resources/config/routing.yml"
    prefix:   /Actualites
fiche:
    resource: "@FicheBundle/Resources/config/routing.yml"
    prefix:   /fiche
etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
rdv:
    resource: "@RdvBundle/Resources/config/routing.yml"
    prefix:   /rdv
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications

