demande_homepage:
    path:     /
    defaults: { _controller: DemandeBundle:Default:index }

ajouter_demande:
    path:     /AjouterDemande
    defaults: { _controller: DemandeBundle:Demande:AjouterDemande }

afficherDemandes:
    path:     /AfficherDemandes
    defaults: { _controller: DemandeBundle:Demande:AfficherDemandes }

declinerDemande:
    path:     /declinerDemande/{id}
    defaults: { _controller: DemandeBundle:Demande:DeclinerDemande }

accepterDemande:
    path:     /accepterDemande/{id}
    defaults: { _controller: DemandeBundle:Demande:AccepterDemande }