actualites_homepage:
    path:     /
    defaults: { _controller: ActualitesBundle:Default:index }

ajouterCategorie:
    path:     /AjouterCategorie
    defaults: { _controller: ActualitesBundle:Categorie:AjouterCategorie }

afficherCategorie:
    path:     /AfficherCategorie
    defaults: { _controller: ActualitesBundle:Categorie:AfficherCategories }

modifierCategorie:
    path:     /ModifierCategorie/{id}
    defaults: { _controller: ActualitesBundle:Categorie:ModifierCategorie}

supprimerCategorie:
    path:     /SupprimerCategorie/{id}
    defaults: { _controller: ActualitesBundle:Categorie:SupprimerCategorie}


ajouterConseil:
    path:     /AjouterConseil
    defaults: { _controller: ActualitesBundle:Conseil:AjouterConseil }


afficherConseils:
    path:     /AfficherConseils
    defaults: { _controller: ActualitesBundle:Conseil:AfficherConseils }

supprimerConseil:
    path:     /SupprimerConseil/{id}
    defaults: { _controller: ActualitesBundle:Conseil:SupprimerConseil }

modifierConseil:
    path:     /ModifierConseil/{id}
    defaults: { _controller: ActualitesBundle:Conseil:ModifierConseil}

ajouterEvenement:
    path:     /AjouterEvenement
    defaults: { _controller: ActualitesBundle:Evenement:AjouterEvenement }

afficherEvenements:
    path:     /AfficherEvenements
    defaults: { _controller: ActualitesBundle:Evenement:AfficherEvenements }

supprimerEvenement:
    path:     /SupprimerEvenement/{id}
    defaults: { _controller: ActualitesBundle:Evenement:SupprimerEvenement }

modifierEvenement:
    path:     /ModifierEvenement/{id}
    defaults: { _controller: ActualitesBundle:Evenement:ModifierEvenement }

indexConseil:
    path:     /indexConseil
    defaults: { _controller: ActualitesBundle:Conseil:indexConseil}

indexEvenement:
    path:     /indexEvenement
    defaults: { _controller: ActualitesBundle:Evenement:indexEvenement}

indexEvenementCat:
    path:     /indexEvenementcat/{id}
    defaults: { _controller: ActualitesBundle:Evenement:AfficherEvenementsCategorie}

detailEvenement:
    path:     /detailEvenement{id}
    defaults: { _controller: ActualitesBundle:Evenement:chercherEvenement}

ajouterComEvent:
    path:     /ajouterComEvent
    defaults: { _controller: ActualitesBundle:CommentaireEvent:AjouterComEvent }

RechercheCurrentDateEvent:
    path:     /RechercheCurrentDateEvent
    defaults: { _controller: ActualitesBundle:Evenement:RechercheCurrentDate }

RechercheDateDemainEvent:
    path:     /RechercheDateDemain
    defaults: { _controller: ActualitesBundle:Evenement:RechercheDateDemain }

RechercheDateSemaineEvent:
    path:     /RechercheDateSemaine
    defaults: { _controller: ActualitesBundle:Evenement:RechercheDateSemaine }

AfficherEvenements3Event:
    path:     /AfficherEvenements3
    defaults: { _controller: ActualitesBundle:Evenement:AfficherEvenements3 }
