

fiche_insertt:
    path:     /insert
    defaults: { _controller: FicheBundle:Fichepatient:insert}

fiche_indexx:
    path:     /
    defaults: { _controller: FicheBundle:Fichepatient:index}
fiche_modifier:
    path:     /modif/{id}
    defaults: { _controller: FicheBundle:Fichepatient:edit}
