
index:
    path:     /
    defaults: { _controller: EtablissementBundle:Etablissement:index}
indexCabinet:
    path:     /indexCabinet
    defaults: { _controller: EtablissementBundle:CabinetMedical:index}
indexCentre:
    path:     /indexCentre
    defaults: { _controller: EtablissementBundle:CentreBeaute:index}
indexHerbo:
    path:     /indexHerbo
    defaults: { _controller: EtablissementBundle:Herboriseterie:index}
indexHopital:
    path:     /indexHopitaux
    defaults: { _controller: EtablissementBundle:Hopitaux:index}
indexLabo:
    path:     /indexLabo
    defaults: { _controller: EtablissementBundle:Laboratoire:index}
indexPara:
    path:     /indexPara
    defaults: { _controller: EtablissementBundle:Parapharmacie:index}
indexPharma:
    path:     /indexPharma
    defaults: { _controller: EtablissementBundle:Pharmacie:index}
indexSalle:
    path:     /indexSalle
    defaults: { _controller: EtablissementBundle:SalleDeSport:index}

insert:
    path:     /insert
    defaults: { _controller: EtablissementBundle:Etablissement:insert}
show:
    path:     /show/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:show}

insertCabinet:
    path:     /insertCabinet
    defaults: { _controller: EtablissementBundle:CabinetMedical:insert}

loadSubEstab:
    path:     /loadsubestab
    defaults: { _controller: EtablissementBundle:Etablissement:loadSubEstablishmentForm}
rating:
    path:     /rate
    defaults: { _controller: EtablissementBundle:Rating:insert}