<?php

namespace ForumBundle\Repository;

/**
 * CommentaireForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireForumRepository extends \Doctrine\ORM\EntityRepository
{
}
