<?php

namespace RdvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RdvRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RdvRepository extends EntityRepository
{
}
