rdv_homepage:
    path:     /
    defaults: { _controller: RdvBundle:Default:index }
affichage:
    path:     /afficher
    defaults: { _controller: RdvBundle:Rdv:afficher}

modifier:
    path:     /modifier/{id}
    defaults: { _controller: RdvBundle:Rdv:edit}
cal:
    path:     /cal
    defaults: { _controller: RdvBundle:Rdv:calendrier}
ajout:
    path:     /ajouterr
    defaults: { _controller: RdvBundle:Rdv:ajouterr}
calAjouter:
    path:     /callin
    defaults: { _controller: RdvBundle:Calendar:insert}
calIndex:
    path:     /callindex
    defaults: { _controller: RdvBundle:Calendar:call}
