<?php

namespace ProductBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('p')
            ->Select('p')
            ->Where('p.idProduit IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
    public function findProduitByName($name){
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.nom LIKE :nom')
            ->setParameter('nom','%'.$name.'%')
            ->getQuery();
        return $qb;
    }

    public function filterProduit($nom,$array){
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.nom LIKE :nom')
            ->andWhere('p.type IN (:array)')
            ->setParameter('array',$array)
            ->setParameter('nom','%'.$nom.'%')
            ->getQuery();
        return $qb;
    }
}
