produits_index:
    path:     /
    defaults: { _controller: "ProductBundle:Produits:index" }
produits_show:
    path:     /{idProduit}/show
    defaults: { _controller: "ProductBundle:Produits:show" }

P_ajouter:
    path:     /{id}/Ajouter
    defaults: { _controller: "ProductBundle:Panier:Ajouter" }

P_supprimmer:
    path:     /{id}/Supprimmer
    defaults: { _controller: "ProductBundle:Panier:Supprimmer" }

P_pass:
    path:     /Pass
    defaults: { _controller: "ProductBundle:Panier:Pass" }

P_basket:
    path:     /Basket
    defaults: { _controller: "ProductBundle:Panier:Basket" }
