produitparapharmacie_index:
    path:     /
    defaults: { _controller: "ProductBundle:ProduitParapharmacie:index" }

produitparapharmacie_show:
    path:     /{idProduit}/show
    defaults: { _controller: "ProductBundle:ProduitParapharmacie:show" }

produitparapharmacie_new:
    path:     /new
    defaults: { _controller: "ProductBundle:ProduitParapharmacie:new" }

produitparapharmacie_edit:
    path:     /{idProduit}/edit
    defaults: { _controller: "ProductBundle:ProduitParapharmacie:edit" }

produitparapharmacie_delete:
    path:     /{idProduit}/delete
    defaults: { _controller: "ProductBundle:ProduitParapharmacie:delete" }
